theme: jekyll-theme-minimal
title: "Charalambos M"
description: "Portfolio, projects, and notes."
author: "Charalambos Maxoutis"
# You can add a custom logo by putting an image in /assets and pointing to it:
# logo: /assets/logo.png

# Optional: site metadata
github_username: charalambosm
# twitter_username: yourhandle
# linkedin_username: your-handle

# Build settings
markdown: kramdown
permalink: pretty
